---
swagger:
  version: 'v4.0.0'
  name: 'meowv_blog'
  title: 'meowv_blog api'
  description: '这里是描述信息'
  routePrefix: ''
  documentTitle: '接口文档'

storage:
  mongodb: 'mongodb://localhost/meowv_blog'

cors:
  policyName: 'meowv-policy'
  origins: 'https://*.meowv.com'

jwt:
  issuer: 'meowv_blog'
  audience: 'meowv_blog api'
  signingKey: 'H4sIAAAAAAAAA3N0cnZxdXP38PTy9vH18w8I9AkOCQ0Lj4iMAgDB4fXPGgAAAA=='