---
swagger:
  version: 'v4.0.0'
  name: 'meowv_blog'
  title: 'meowv_blog api'
  description: 'Powered by .NET 5.0 on Linux'
  routePrefix: ''
  documentTitle: 'meowv_blog api'

storage:
  mongodb: 'mongodb://localhost/meowv_blog'
  redisIsEnabled: true
  redis: '127.0.0.1'

cors:
  policyName: 'meowv-policy'
  origins: 'https://*.meowv.com'

jwt:
  issuer: 'meowv_blog'
  audience: 'meowv_blog api'
  signingKey: 'H4sIAAAAAAAAA3N0cnZxdXP38PTy9vH18w8I9AkOCQ0Lj4iMAgDB4fXPGgAAAA=='

worker:
  isEnabled: true
  cron: '0 * * * * ? *'

authorize:
  account:
    username: 'admin'
    password: 'admin'
  github:
  gitee:
  microsoft:
  qq:
  weibo:
  baidu:
  dingtalk:
  alipay: