---
swagger:
  version: 'v4.0.0'
  name: 'meowv_blog'
  title: 'meowv_blog api'
  description: 'Powered by .NET 5.0 on Linux'
  routePrefix: ''
  documentTitle: 'meowv_blog api'

storage:
  mongodb: 'mongodb://localhost/meowv_blog'
  redisIsEnabled: true
  redis: '127.0.0.1'

cors:
  policyName: 'meowv-policy'
  origins: 'https://*.meowv.com'

jwt:
  issuer: 'meowv_blog'
  audience: 'meowv_blog api'
  signingKey: 'H4sIAAAAAAAAA3N0cnZxdXP38PTy9vH18w8I9AkOCQ0Lj4iMAgDB4fXPGgAAAA=='

worker:
  isEnabled: true
  cron: '0 0 0/1 * * ? *'

signature:
  path: 'D:\static\signature'
  urls:
  - url: 'https://api1.meowv.com'
    param: '1'
  - url: 'https://api2.meowv.com'
    param: '2'
  - url: 'https://api3.meowv.com'
    param: '3'

authorize:
  github:
    clientId: 'e31df3ad90fb05adc29c'
    clientSecret: 'bd022aff3e8d58c18cfe0889e00013775b9b737d'
    redirectUrl: 'https://localhost:5001/api/meowv/oauth/github/token'
    scope: 'user'
  gitee:
    clientId: '2aa9116886160b7a7d5d87f043df4f3331d15ac1b1f3b57844d87e0b7b62e9c2'
    clientSecret: 'ae2380c4b66e0c3420875d65a03102eb71e8802ef4356eb23224486e701219a1'
    redirectUrl: 'https://localhost:5001/api/meowv/oauth/gitee/token'
    scope: 'user_info emails'